apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: syfomoteoversikt
  namespace: teamsykefravr
  labels:
    team: teamsykefravr
spec:
  image: {{ image }}
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /health/isAlive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /health/isReady
    initialDelay: 30
    periodSeconds: 5
    timeout: 5
  prometheus:
    enabled: true
    path: /actuator/metrics
  resources:
    limits:
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 128Mi
  azure:
    sidecar:
      enabled: true
      autoLogin: true
    application:
      allowAllUsers: true
      enabled: true
      tenant: trygdeetaten.no
      claims:
        extra:
          - "NAVident"
  valkey:
    - instance: cache
      access: readwrite
  accessPolicy:
    outbound:
      external:
        - host: "login.microsoftonline.com"
        - host: "ereg-services-q1.dev-fss-pub.nais.io"
      rules:
        - application: isdialogmote
        - application: syfoveileder
        - application: syfoperson
        - application: modiacontextholder
          namespace: personoversikt
  envFrom:
    - secret: syfomoteoversikt-session-key
  ingresses:
    - "https://syfomoteoversikt.intern.dev.nav.no"
    - "https://syfomoteoversikt.ansatt.dev.nav.no"
  env:
    - name: NODE_ENV
      value: "production"
    - name: AUTH_REDIRECT_URI
      value: "https://syfomoteoversikt.intern.dev.nav.no/oauth2/callback"
    - name: EREG_HOST
      value: "https://ereg-services-q1.dev-fss-pub.nais.io"
    - name: ISDIALOGMOTE_HOST
      value: "http://isdialogmote"
    - name: ISDIALOGMOTE_AAD_APP_CLIENT_ID
      value: "dev-gcp.teamsykefravr.isdialogmote"
    - name: MODIACONTEXTHOLDER_AAD_APP_CLIENT_ID
      value: "dev-gcp.personoversikt.modiacontextholder"
    - name: MODIACONTEXTHOLDER_HOST
      value: "http://modiacontextholder.personoversikt"
    - name: SYFOPERSON_AAD_APP_CLIENT_ID
      value: "dev-gcp.teamsykefravr.syfoperson"
    - name: SYFOPERSON_HOST
      value: "http://syfoperson"
    - name: SYFOVEILEDER_AAD_APP_CLIENT_ID
      value: "dev-gcp.teamsykefravr.syfoveileder"
    - name: SYFOVEILEDER_HOST
      value: "http://syfoveileder"
