apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: syfomoteoversikt
  namespace: teamsykefravr
  labels:
    team: teamsykefravr
spec:
  image: {{ image }}
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /health/isAlive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /health/isReady
    initialDelay: 30
    periodSeconds: 5
    timeout: 5
  prometheus:
    enabled: true
    path: /actuator/metrics
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 128Mi
  azure:
    application:
      allowAllUsers: true
      enabled: true
      tenant: nav.no
      replyURLs:
        - "https://syfomoteoversikt.intern.nav.no/oauth2/callback"
      claims:
        extra:
          - "NAVident"
  envFrom:
    - secret: syfomoteoversikt-session-key
  webproxy: true
  ingresses:
    - "https://syfomoteoversikt.intern.nav.no"
  env:
    - name: NODE_ENV
      value: "production"
    - name: AUTH_REDIRECT_URI
      value: "https://syfomoteoversikt.intern.nav.no/oauth2/callback"
    - name: REDIS_HOST
      value: "syfomoteoversikt-redis"
    - name: EREG_HOST
      value: "ereg-services.intern.nav.no"
    - name: INTERNARBEIDSFLATEDECORATOR_HOST
      value: "internarbeidsflatedecorator.intern.nav.no"
    - name: ISDIALOGMOTE_HOST
      value: "isdialogmote.intern.nav.no"
    - name: ISDIALOGMOTE_AAD_APP_CLIENT_ID
      value: "prod-gcp.teamsykefravr.isdialogmote"
    - name: MODIACONTEXTHOLDER_AAD_APP_CLIENT_ID
      value: "prod-fss.personoversikt.modiacontextholder"
    - name: MODIACONTEXTHOLDER_HOST
      value: "modiacontextholder.intern.nav.no"
    - name: SYFOPERSON_AAD_APP_CLIENT_ID
      value: "prod-gcp.teamsykefravr.syfoperson"
    - name: SYFOPERSON_HOST
      value: "syfoperson.intern.nav.no"
    - name: SYFOSMREGISTER_AAD_APP_CLIENT_ID
    - name: SYFOVEILEDER_AAD_APP_CLIENT_ID
      value: "prod-gcp.teamsykefravr.syfoveileder"
    - name: SYFOVEILEDER_HOST
      value: "syfoveileder.intern.nav.no"
