export const PUSH_MODIACONTEXT_FORESPURT = 'PUSH_MODIACONTEXT_FORESPURT';
export const PUSH_MODIACONTEXT_FEILET = 'PUSH_MODIACONTEXT_FEILET';
export const MODIACONTEXT_PUSHET = 'MODIACONTEXT_PUSHET';
export const PUSHER_MODIACONTEXT = 'PUSHER_MODIACONTEXT';

export const HENT_AKTIVENHET_FORESPURT = 'HENT_AKTIVENHET_FORESPURT';
export const HENTER_AKTIVENHET = 'HENTER_AKTIVENHET';
export const HENT_AKTIVENHET_FEILET = 'HENT_AKTIVENHET_FEILET';
export const AKTIVENHET_HENTET = 'AKTIVENHET_HENTET';

export const TOGGLE_FANE_VISNING = 'TOGGLE_FANE_VISNING';

export const HENTER_LEDETEKSTER = 'HENTER_LEDETEKSTER';
export const LEDETEKSTER_HENTET = 'LEDETEKSTER_HENTET';
export const HENT_LEDETEKSTER_FEILET = 'HENT_LEDETEKSTER_FEILET';
export const HENT_LEDETEKSTER_FORESPURT = 'HENT_LEDETEKSTER_FORESPURT';
