name: main

on: push

jobs:
  build-and-deploy:
    permissions:
      contents: read
      id-token: write
    uses: navikt/isworkflows/.github/workflows/node-build-deploy.yml@master
    with:
      node-version: 18
      distroless: true
    secrets: inherit
